sudo: required
# We need the systemd for the kubeadm and it's default from 16.04+
dist: xenial
env:
  global:
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config

before_script:
# kubectl
- curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
# minikube
- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.0.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
- mkdir -p $HOME/.kube $HOME/.minikube
- touch $KUBECONFIG
- sudo minikube start --vm-driver=none --kubernetes-version=v1.13.0 --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
- "sudo chown -R travis: /home/travis/.minikube/"

script:
- kubectl cluster-info
- kubectl apply -f deploy/crds/serving_v1alpha1_knativeserving_crd.yaml
- kubectl apply -n default -f deploy/
- kubectl apply -n default -f deploy/crds/serving_v1alpha1_knativeserving_cr.yaml
- sleep 30
- kubectl get pod --all-namespaces
- kubectl logs deployment/knative-serving-operator
- sleep 30
- kubectl get pod --all-namespaces
- kubectl logs deployment/knative-serving-operator
- sleep 30
- kubectl get pod --all-namespaces
- kubectl logs deployment/knative-serving-operator
- sleep 30
- kubectl get pod --all-namespaces
- kubectl logs deployment/knative-serving-operator
- sleep 30
- kubectl get pod --all-namespaces
- kubectl logs deployment/knative-serving-operator
- sleep 30
- kubectl get pod --all-namespaces
- kubectl logs deployment/knative-serving-operator
