apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-serving-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knative-serving-operator
  template:
    metadata:
      labels:
        name: knative-serving-operator
    spec:
      serviceAccountName: knative-serving-operator
      containers:
        - name: knative-serving-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - knative-serving-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "knative-serving-operator"
